server:
  port: 8039


spring:
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:file:~/testdb
      initialization-mode: always
      platform: h2
      username: sa
      password:
      driverClassName: org.h2.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
